// Generated by tools/generate-weather-icon-fonts.mjs from
// tools/weather-icons/parts.mjs. Do not edit by hand.
#pragma once

#include <stdint.h>

namespace weather_icon_table {

// Label text per MDI weather icon name for the weather icon font with label
// recoloring: every "#RRGGBB <glyph>#" draws one icon layer. Layer glyphs have
// no advance, so all layers share one position; the closing spacer glyph gives
// the icon the MDI advance width.
struct Entry {
  const char* name;
  const char* text;
};

inline constexpr uint32_t kFirstCodepoint = 0xE000;
inline constexpr uint32_t kLastCodepoint = 0xE017;

inline constexpr Entry kEntries[] = {
    {"weather-sunny", "#FFC53D " "\xEE\x80\x81" "#" "\xEE\x80\x80"},
    {"weather-night", "#FFE08A " "\xEE\x80\x82" "#" "#FFFFFF " "\xEE\x80\x83" "#" "\xEE\x80\x80"},
    {"weather-partly-cloudy", "#FFC53D " "\xEE\x80\x84" "#" "#EEF2F7 " "\xEE\x80\x85" "#" "\xEE\x80\x80"},
    {"weather-cloudy", "#8E9BB0 " "\xEE\x80\x86" "#" "#C3CCD8 " "\xEE\x80\x87" "#" "\xEE\x80\x80"},
    {"weather-fog", "#C3CCD8 " "\xEE\x80\x88" "#" "#8E9BB0 " "\xEE\x80\x89" "#" "\xEE\x80\x80"},
    {"weather-rainy", "#EEF2F7 " "\xEE\x80\x8A" "#" "#4DA3FF " "\xEE\x80\x8B" "#" "\xEE\x80\x80"},
    {"weather-pouring", "#C3CCD8 " "\xEE\x80\x8A" "#" "#4DA3FF " "\xEE\x80\x8C" "#" "\xEE\x80\x80"},
    {"weather-snowy", "#EEF2F7 " "\xEE\x80\x8A" "#" "#CFE8FF " "\xEE\x80\x8D" "#" "\xEE\x80\x80"},
    {"weather-snowy-rainy", "#EEF2F7 " "\xEE\x80\x8A" "#" "#CFE8FF " "\xEE\x80\x8E" "#" "#4DA3FF " "\xEE\x80\x8F" "#" "\xEE\x80\x80"},
    {"weather-hail", "#C3CCD8 " "\xEE\x80\x8A" "#" "#CFE8FF " "\xEE\x80\x90" "#" "\xEE\x80\x80"},
    {"weather-lightning", "#9EAABA " "\xEE\x80\x8A" "#" "#FFC53D " "\xEE\x80\x91" "#" "\xEE\x80\x80"},
    {"weather-lightning-rainy", "#9EAABA " "\xEE\x80\x8A" "#" "#FFC53D " "\xEE\x80\x92" "#" "#4DA3FF " "\xEE\x80\x93" "#" "\xEE\x80\x80"},
    {"weather-windy", "#A9C7E8 " "\xEE\x80\x94" "#" "\xEE\x80\x80"},
    {"weather-windy-variant", "#C3CCD8 " "\xEE\x80\x95" "#" "#A9C7E8 " "\xEE\x80\x96" "#" "\xEE\x80\x80"},
    {"alert-circle-outline", "#FFB020 " "\xEE\x80\x97" "#" "\xEE\x80\x80"},
};

}  // namespace weather_icon_table
